# Window Rules

## OBS
windowrule=globalkeybinding:ctrl+alt-o,appid:com.obsproject.Studio
windowrule=globalkeybinding:ctrl+alt-n,appid:com.obsproject.Studio

## Flameshot
windowrule=noswallow:1,appid:flameshot
windowrule=isfullscreen:1,appid:flameshot
windowrule=animation_type_open:none,appid:flameshot
windowrule=animation_type_close:none,appid:flameshot
windowrule=isfloating:1,appid:flameshot
windowrule=width:1500,height:900,appid:flameshot

# signal
#windowrule=isfloating:1,appid:signal

## Steam
windowrule=isfloating:1,appid:steam

## Blueman
windowrule=isfloating:1,appid:blueman-manager
windowrule=width:1500,height:900,appid:blueman-manager


# windowrule=isfloating:1,appid:xfce-polkit


windowrule=isterm:1,appid:Alacritty
windowrule=isterm:1,appid:kitty

# tag placement
windowrule=tags:2,appid:firefox
windowrule=tags:3,appid:mpv
windowrule=tags:3,appid:cafe.avery.Delfin
windowrule=tags:6,appid:steam
windowrule=tags:5,appid:signal
windowrule=tags:4,appid:obs

windowrule=isfloating:1,isoverlay:1,isnoborder:1,isunglobal:1,width:280,height:200,offsetx:9999,offsety:9999,appid:mpv,title:video0 - mpv


windowrule=unfocused_opacity:1.0,focused_opacity:1.0,appid:^mpv$
windowrule=unfocused_opacity:1.0,focused_opacity:1.0,appid:^cafe.avery.Delfin$


# tags rule
tagrule=id:1,no_hide:1,layout_name:tile
tagrule=id:2,no_hide:1,layout_name:tile
tagrule=id:3,no_hide:1,layout_name:tile
tagrule=id:4,no_hide:1,layout_name:tile
tagrule=id:5,no_hide:1,layout_name:tile
tagrule=id:6,no_hide:1,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# layer rule
layerrule=noblur:1,noanim:1,layer_name:selection
layerrule=noshadow:1,layer_name:swaync-control-center
layerrule=noshadow:1,layer_name:swaync-notification-window
layerrule=noblur:1,noanim:1,layer_name:dimland_layer
layerrule=noanim:1,noblur:1,noshadow:1,layer_name:cafe.avery.Delfin
layerrule=noanim:1,layer_name:showkeys
layerrule=noanim:1,noblur:1,noshadow:1,layer_name:fuzzel
layerrule=noshadow:1,layer_name:waybar
